// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: communication/comm.proto

package comm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Vvt           *Vvector               `protobuf:"bytes,4,opt,name=vvt,proto3" json:"vvt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_communication_comm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_communication_comm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_communication_comm_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Message) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetVvt() *Vvector {
	if x != nil {
		return x.Vvt
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_communication_comm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_communication_comm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_communication_comm_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T             []int64                `protobuf:"varint,1,rep,packed,name=t,proto3" json:"t,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_communication_comm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_communication_comm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_communication_comm_proto_rawDescGZIP(), []int{2}
}

func (x *Vector) GetT() []int64 {
	if x != nil {
		return x.T
	}
	return nil
}

type Vvector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             []*Vector              `protobuf:"bytes,1,rep,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vvector) Reset() {
	*x = Vvector{}
	mi := &file_communication_comm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vvector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vvector) ProtoMessage() {}

func (x *Vvector) ProtoReflect() protoreflect.Message {
	mi := &file_communication_comm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vvector.ProtoReflect.Descriptor instead.
func (*Vvector) Descriptor() ([]byte, []int) {
	return file_communication_comm_proto_rawDescGZIP(), []int{3}
}

func (x *Vvector) GetV() []*Vector {
	if x != nil {
		return x.V
	}
	return nil
}

var File_communication_comm_proto protoreflect.FileDescriptor

const file_communication_comm_proto_rawDesc = "" +
	"\n" +
	"\x18communication/comm.proto\x1a\x1bgoogle/protobuf/empty.proto\"c\n" +
	"\aMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\x03vvt\x18\x04 \x01(\v2\b.vvectorR\x03vvt\"\x19\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x06vector\x12\f\n" +
	"\x01t\x18\x01 \x03(\x03R\x01t\" \n" +
	"\avvector\x12\x15\n" +
	"\x01v\x18\x01 \x03(\v2\a.vectorR\x01v2\xa1\x01\n" +
	"\rCommunication\x12(\n" +
	"\x04Send\x12\b.Message\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12.\n" +
	"\n" +
	"Disconnect\x12\b.Request\x1a\x16.google.protobuf.EmptyB Z\x1egithub.com/KTNguyen04/SES/commb\x06proto3"

var (
	file_communication_comm_proto_rawDescOnce sync.Once
	file_communication_comm_proto_rawDescData []byte
)

func file_communication_comm_proto_rawDescGZIP() []byte {
	file_communication_comm_proto_rawDescOnce.Do(func() {
		file_communication_comm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_communication_comm_proto_rawDesc), len(file_communication_comm_proto_rawDesc)))
	})
	return file_communication_comm_proto_rawDescData
}

var file_communication_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_communication_comm_proto_goTypes = []any{
	(*Message)(nil),       // 0: Message
	(*Request)(nil),       // 1: Request
	(*Vector)(nil),        // 2: vector
	(*Vvector)(nil),       // 3: vvector
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_communication_comm_proto_depIdxs = []int32{
	3, // 0: Message.vvt:type_name -> vvector
	2, // 1: vvector.v:type_name -> vector
	0, // 2: Communication.Send:input_type -> Message
	4, // 3: Communication.Ping:input_type -> google.protobuf.Empty
	1, // 4: Communication.Disconnect:input_type -> Request
	4, // 5: Communication.Send:output_type -> google.protobuf.Empty
	4, // 6: Communication.Ping:output_type -> google.protobuf.Empty
	4, // 7: Communication.Disconnect:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_communication_comm_proto_init() }
func file_communication_comm_proto_init() {
	if File_communication_comm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_communication_comm_proto_rawDesc), len(file_communication_comm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communication_comm_proto_goTypes,
		DependencyIndexes: file_communication_comm_proto_depIdxs,
		MessageInfos:      file_communication_comm_proto_msgTypes,
	}.Build()
	File_communication_comm_proto = out.File
	file_communication_comm_proto_goTypes = nil
	file_communication_comm_proto_depIdxs = nil
}
